### ISSUE TITLE
After pressing "beitreten" nothing happens

### ISSUE THREAD

**Issue by davidh38** [HenriWahl/doko3000#1]
Hello Henri,
if i run docker-compose:
docker-compose -f docker/docker-compose.yml up -d
![image](https://user-images.githubusercontent.com/15130290/107512594-541f9b00-6ba7-11eb-94ff-5f0f0404531b.png)

How do i know, how many players are at the table? How do i start the table, i cannot see a menu on the left upper corner like shown in the readme

in the browser i get the following error, if that helps:
![image](https://user-images.githubusercontent.com/15130290/107513000-e3c54980-6ba7-11eb-8c4f-2d2a17f39eb4.png)

**Comment by HenriWahl** [comment]
When a player entered the table it will be listed in the table view:

![grafik](https://user-images.githubusercontent.com/2835065/107525971-a8327b80-6bb7-11eb-9193-472521ccac12.png)

According to your second screenshot the websocket is not available. I will check if I get the same result when starting via docker-compose like you did.

**Comment by HenriWahl** [comment]
> According to your second screenshot the websocket is not available. I will check if I get the same result when starting via docker-compose like you did.

I run 
`cp docker/default.env .env`
and
`docker-compose -f docker/docker-compose.yml up -d`
from latest master and it works.
What might influence the websockets on your testing machine?
What OS do you run it on? I run it on Linux.
Can you try to run it without nginx?

**Comment by HenriWahl** [comment]
In https://github.com/miguelgrinberg/Flask-SocketIO/issues/298 this problem is solved by setting `cors_allowed_origins`. Doko3000 should ignore this if it is not set, but just in case you can set it in the `.env` file like in https://github.com/HenriWahl/doko3000/blob/master/docker/default.env#L3.

**Edit:** I think I got it: I set the CORS HOST variable in .env and called the app like you via http://127.0.0.1 - both do not match. Either leave .env without HOST or call it like it is set in .env. Apparently it is not set to 127.0.0.1.

**Comment by davidh38** [comment]
I am on Ubuntu 20.04, but if i leave it, i get nginx 502 Bad Gateway.
I set it to 127.0.0.1 and left it out and i tried without nginx.

I am just cloning the repo and enter the directory: doko3000
then i run: cp docker/default.env .env
and after that:
docker-compose -f ./docker/docker-compose.yml up -d
and then starting: 0.0.0.0 in the browser.
Am i missing something?

**Comment by HenriWahl** [comment]
Can you call http://localhost when using docker-compose?
If trying without nginx, you might need to run http://localhost:3000.

**Comment by HenriWahl** [comment]
You can send your .env and your docker-compose.yml so I can test with your setup.

**Comment by davidh38** [comment]
Thank you @HenriWahl, i am using exactly your docker-compose.yml and your .env file.

**Comment by HenriWahl** [comment]
> and then starting: 0.0.0.0 in the browser.

And really starting with 0.0.0.0?

Regarding the 502 error in nginx: are you sure all 3 containers are running? Maybe run `docker-compose up` without -d to see the container output.

**Edit:** It works for me even with the 0.0.0.0 address and no HOST set in .env file. I tested in Chrome and Firefox.

**Comment by HenriWahl** [comment]
Can you try this shrinked docker-compose.yml without nginx:
```
version: '3.7'

networks:
  doko3000:
    name: doko3000

volumes:
  doko3000-couchdb-config:
  doko3000-couchdb-data:

services:
  doko3000:
    build: ..
    image: doko3000
    container_name: doko3000
    restart: always
    networks:
      - doko3000
    environment:
      - HOST
      - SECRET_KEY
      - COUCHDB_USER
      - COUCHDB_PASSWORD
    ports:
      - 80:5000/tcp
  couchdb:
    image: couchdb
    container_name: doko3000-couchdb
    restart: always
    volumes:
      - doko3000-couchdb-data:/opt/couchdb/data
      - doko3000-couchdb-config:/opt/couchdb/etc/local.d
    networks:
      - doko3000
    environment:
      - COUCHDB_USER
      - COUCHDB_PASSWORD
```
With an .env like this - otherwise CouchDB won't be initialized:
```
COUCHDB_USER=admin
COUCHDB_PASSWORD=doko3000
SECRET_KEY=change_me
```
And access via http://localhost
